from __future__ import annotations

import email.parser
import email.policy
import hashlib
import pathlib
import re
import shutil
import sys
import tomllib
import zipfile

LOCK_REQUIREMENT = re.compile(r"([A-Za-z0-9_.-]+)==([A-Za-z0-9][A-Za-z0-9._+!-]*) \\")
LOCK_HASH = re.compile(r"    --hash=sha256:[0-9a-f]{64}")
SAFE_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
SAFE_VERSION = re.compile(r"[A-Za-z0-9][A-Za-z0-9._+!-]*")
MAX_METADATA_SIZE = 1024 * 1024
VALIDATION_ONLY = frozenset({"build", "pytest", "ruff", "setuptools"})
PROJECT_BUILD_PATHS = ("pyproject.toml", "README.md", "LICENSE", "src")
IGNORED_BUILD_NAMES = frozenset({"__pycache__", ".pytest_cache", ".ruff_cache"})


class LockError(ValueError):
    pass


def canonicalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def project_roots(pyproject_path: pathlib.Path, profile: str) -> list[str]:
    if profile not in {"runtime", "validation"}:
        raise LockError(f"unknown lock profile: {profile}")
    configuration = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    project = configuration["project"]
    requirements = list(project.get("dependencies", []))
    optional = project.get("optional-dependencies", {})
    requirements.extend(optional.get("ssh", []))
    if profile == "validation":
        requirements.extend(optional.get("dev", []))
    if not requirements:
        raise LockError(f"no dependency roots were found for {profile}")
    if any(
        not requirement or "\n" in requirement or "\r" in requirement
        for requirement in requirements
    ):
        raise LockError("project requirement is empty or contains a newline")
    return requirements


def _wheel_digest(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _wheel_identity(path: pathlib.Path) -> tuple[str, str]:
    try:
        with zipfile.ZipFile(path) as archive:
            records = [
                info
                for info in archive.infolist()
                if info.filename.endswith(".dist-info/METADATA") and info.filename.count("/") == 1
            ]
            if len(records) != 1 or records[0].file_size > MAX_METADATA_SIZE:
                raise LockError(f"wheel has an ambiguous or oversized METADATA record: {path.name}")
            metadata = email.parser.BytesParser(policy=email.policy.default).parsebytes(
                archive.read(records[0])
            )
    except (OSError, zipfile.BadZipFile) as error:
        raise LockError(f"wheel cannot be read: {path.name}") from error
    name = metadata.get("Name", "")
    version = metadata.get("Version", "")
    if SAFE_NAME.fullmatch(name) is None or SAFE_VERSION.fullmatch(version) is None:
        raise LockError(f"wheel metadata has an unsafe name or version: {path.name}")
    return name, version


def generate_lock(wheel_directory: pathlib.Path, output: pathlib.Path, profile: str) -> None:
    if profile == "runtime":
        description = "project dependencies plus the ssh extra"
    elif profile == "validation":
        description = "project dependencies plus the ssh and dev extras"
    else:
        raise LockError(f"unknown lock profile: {profile}")
    if not wheel_directory.is_dir() or wheel_directory.is_symlink():
        raise LockError(f"wheel directory is missing or unsafe: {wheel_directory}")

    entries: dict[str, tuple[str, str, str]] = {}
    for wheel in sorted(wheel_directory.iterdir()):
        if not wheel.is_file() or wheel.is_symlink() or wheel.suffix != ".whl":
            raise LockError(f"resolver returned a non-wheel artifact: {wheel.name}")
        name, version = _wheel_identity(wheel)
        canonical_name = canonicalize(name)
        if canonical_name in entries:
            raise LockError(f"resolver returned duplicate wheels for {name}")
        entries[canonical_name] = (name, version, _wheel_digest(wheel))
    if not entries:
        raise LockError("resolver returned no wheels")

    lines = [
        "# Generated by scripts/vm-locks update for CPython 3.11 x86_64 Linux.",
        f"# Profile: {description}.",
    ]
    for canonical_name in sorted(entries):
        name, version, digest = entries[canonical_name]
        lines.extend((f"{name}=={version} \\", f"    --hash=sha256:{digest}"))
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def copy_project_source(source: pathlib.Path, destination: pathlib.Path) -> None:
    if destination.exists() or destination.is_symlink():
        raise LockError(f"project staging destination already exists: {destination}")
    destination.mkdir(mode=0o700)
    for relative_name in PROJECT_BUILD_PATHS:
        source_path = source / relative_name
        destination_path = destination / relative_name
        if source_path.is_symlink() or not source_path.exists():
            raise LockError(f"project build input is missing or unsafe: {relative_name}")
        if source_path.is_file():
            shutil.copy2(source_path, destination_path, follow_symlinks=False)
            continue
        if not source_path.is_dir():
            raise LockError(f"project build input is not regular: {relative_name}")
        destination_path.mkdir()
        for item in sorted(source_path.rglob("*")):
            item_relative = item.relative_to(source_path)
            if any(
                part in IGNORED_BUILD_NAMES or part.endswith(".egg-info")
                for part in item_relative.parts
            ) or item.suffix in {".pyc", ".pyo"}:
                continue
            staged_item = destination_path / item_relative
            if item.is_symlink():
                raise LockError(
                    f"project build input contains a link: {relative_name}/{item_relative}"
                )
            if item.is_dir():
                staged_item.mkdir(exist_ok=True)
            elif item.is_file():
                shutil.copy2(item, staged_item, follow_symlinks=False)
            else:
                raise LockError(
                    f"project build input is not regular: {relative_name}/{item_relative}"
                )


def _read_lock_entries(path: pathlib.Path) -> dict[str, tuple[str, str]]:
    if not path.is_file() or path.is_symlink():
        raise LockError(f"lock file is missing or unsafe: {path}")
    content = path.read_text(encoding="utf-8").splitlines()
    entries: dict[str, tuple[str, str]] = {}
    order: list[str] = []
    index = 0
    while index < len(content):
        line = content[index]
        index += 1
        if not line or line.startswith("#"):
            continue
        match = LOCK_REQUIREMENT.fullmatch(line)
        if match is None or index >= len(content):
            raise LockError(f"malformed pinned requirement in {path}: {line!r}")
        hash_line = content[index]
        index += 1
        if LOCK_HASH.fullmatch(hash_line) is None:
            raise LockError(f"malformed wheel hash in {path}: {hash_line!r}")
        canonical_name = canonicalize(match.group(1))
        order.append(canonical_name)
        entries[canonical_name] = (match.group(2), hash_line)
    if not order or len(order) != len(entries):
        raise LockError(f"lock file is empty or has duplicate projects: {path}")
    if order != sorted(order):
        raise LockError(f"lock file is not sorted canonically: {path}")
    return entries


def read_lock(path: pathlib.Path) -> list[str]:
    return list(_read_lock_entries(path))


def validate_lock_contract(validation_path: pathlib.Path, runtime_path: pathlib.Path) -> None:
    validation = _read_lock_entries(validation_path)
    runtime = _read_lock_entries(runtime_path)
    if not runtime.keys() < validation.keys():
        raise LockError("runtime lock must be a strict subset of the validation lock")
    unexpected = sorted(runtime.keys() & VALIDATION_ONLY)
    if unexpected:
        raise LockError(f"validation-only projects appear in runtime lock: {', '.join(unexpected)}")
    mismatched = sorted(name for name, pin in runtime.items() if validation[name] != pin)
    if mismatched:
        raise LockError(
            "runtime and validation locks disagree on shared pins: " + ", ".join(mismatched)
        )


def main(arguments: list[str] | None = None) -> int:
    values = sys.argv[1:] if arguments is None else arguments
    try:
        if len(values) == 3 and values[0] == "roots":
            for requirement in project_roots(pathlib.Path(values[1]), values[2]):
                print(requirement)
            return 0
        if len(values) == 4 and values[0] == "generate":
            generate_lock(pathlib.Path(values[1]), pathlib.Path(values[2]), values[3])
            return 0
        if len(values) == 3 and values[0] == "copy-source":
            copy_project_source(pathlib.Path(values[1]), pathlib.Path(values[2]))
            return 0
        if len(values) == 3 and values[0] == "validate":
            validate_lock_contract(pathlib.Path(values[1]), pathlib.Path(values[2]))
            return 0
    except (KeyError, LockError, OSError, tomllib.TOMLDecodeError) as error:
        print(f"vm-locks: {error}", file=sys.stderr)
        return 1
    print("usage: vm_locks.py roots|generate|copy-source|validate ...", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
